### ISSUE TITLE
Various step sizes / Predefined all values

### ISSUE THREAD

**Issue by pavelloz** [egorkhmelev/jslider#83]
Hi,

First of all - thanks for developing this plugin, its great :)

I have a problem, I need to give user couple options to choose from, exactly:
12, 18, 24, 36, 48, 60

Of course I set smooth false, from 12, to 60, default value 60, but when i set my scale and heterogonity:

``` javascript
from: 12,
to: 60,
step: 6,
smooth: false,
scale: ['12', '18', '24', '36', '48', '60'],
heterogenity: ['20/12', '33/18', '40/24', '80/48'],
```

It produces wrong scale. If i set heterogenity alone, its ok, but then scale is unknown.

There is one unusual value there, 18, which cant be accessed by step 12, and if i set step 6, ofcourse it will select couple points that i dont want to.

Heres the screenshot with initial value 36:
![var ranges](https://f.cloud.github.com/assets/546845/1428928/3f9e4ada-40aa-11e3-863f-bf6c6f572c32.PNG)

I would be grateful for any idea how to solve this problem

For future i give my point of view: I should be able to set all available values, apart from the range. That would allow me to set some more precise points.

Other way around, if I could set different step sizes for different data ranges it would also be helpful in current conditions.

Regards,
Paweł

**Comment by chenrycommit** [comment]
I'm having the same problem (using 9 options) and heterogeneity seems like the answer, but I can't figure it out based on your example.
